export * from './getTodayDate'
export * from './qrToRecibir'
export * from './qrTableData'
export * from './qrScannerToObject'
export * from './materialTypes'
export * from './checkDuplicates'
export * from './qrScannerToObjectArray'